\c products;

INSERT INTO 
    products(name, url, type, description, rating, is_favorite) 
VALUES
    ('Cinnamon', 'https://images.everydayhealth.com/images/tiktok-cinnamon-trends-1440x810.jpg?sfvrsn=b040a061_4', 'spice', 'Used as a spice for thousands of years, cinnamon comes from the bark of various species of cinnamon trees. The leaves, flowers, fruits, and roots of cinnamon trees have also been used in cooking and for medicinal purposes.' , '5', true),
    ('Cardamom', 'https://www.ritualzeroproof.com/cdn/shop/articles/cardamom_b5c86e52-01e2-4f66-825a-1585deaab367.jpg?v=1658854939', 'spice',  'Cardamom is used to spice both sweet and savory dishes. It is widely employed in Indian, Middle Eastern, Arabic, and Swedish cuisine. It comes in two types and is used as whole pods, seeds, or ground.', '4', true),
    ('Nutmeg', 'https://betterme.world/articles/wp-content/uploads/2022/06/shutterstock_736972447.jpg', 'spice', 'Nutmeg is the spice made by grinding the seed of the fragrant nutmeg tree (Myristica fragrans) into powder. The spice has a distinctive pungent fragrance and a warm, slightly sweet taste.', '4', true),
    ('Lion''s mane', 'https://i.insider.com/624c639c16e2c40019666fbd?width=1000&format=jpeg&auto=webp', 'fungi', 'Lion''s mane (Hericium erinaceus) is a mushroom that grows on trunks of dead hardwood trees such as oak. It has a long history of use in East Asian medicine.', '3', true),
    ('Cordyceps', 'https://foragerchef.com/wp-content/uploads/2018/04/Cordyceps-1.jpg', 'fungi', 'Cordyceps is a fungus that lives on certain caterpillars in the high mountain regions of China. It is sometimes used as a medicine.', '4', true),
    ('Chamomile', 'https://www.saratogateaandhoney.com/cdn/shop/products/Chamomileflowers-769-Edit.jpg?v=1617383771', 'herb', 'Two of the species, Matricaria chamomilla and Chamaemelum nobile, are commonly used to make herbal infusions for beverages.', '5', true),
    ('Spirulina', 'https://post.healthline.com/wp-content/uploads/2020/09/spirulina-732x549-thumbnail.jpg', 'algae', 'Spirulina is a type of algae that grows in fresh or salt water. It comes as a supplement, in tablet or powder form. People use it for its health benefits, as it is rich in nutrients and has antioxidant properties.', '5', true),
    ('Flaxseed', 'https://images.healthshots.com/healthshots/en/uploads/2021/04/26122331/side-effects-of-flax-seeds.jpg', 'seed', 'Flaxseed comes from the flax plant (also known as Linum usitatissimum). Its nutty-tasting seeds can be eaten on their own or crushed and cold-pressed to release flaxseed oil. For decades, it was common to find flaxseed (also called linseed) used in things like cereal or bread.', '3', true),
    ('Matcha', 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-913054872-1562740834.jpg', 'green tea', 'Matcha is a high-grade green tea ground into powdered form. The green tea powder is whisked into hot water, instead of steeped, to form a frothy drink.', '5', true),
    ('Shilajit', 'https://t4.ftcdn.net/jpg/05/32/68/43/360_F_532684374_6EGVNKApDS4RPpbMFV6YqixPci03RUUc.jpg', 'resin', 'Shilajit is a mineral-rich resin tha has been known and used for centuries in the Ayurvedic system of medicine. It is a blackish-brown powder or exudate obtained from high mountain rocks in the Himalayan mountains between India and Nepal.', '4', true);